[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch>=9.0.1",
    "fastapi>=0.115.12",
    "python-dotenv>=1.1.0",
]
